### ISSUE TITLE
setPassword method

### ISSUE THREAD

**Issue by D4fnk** [nuxeo/nuxeo-java-client#10]
Hey,

I saw that on commit 6a74bdd the setPassword method has been removed, yet the instruction newUser.setPassword is still used on the doc page.
My question is, using Java Client how do you set the User Password ? (i can create a user juste fine but can't connect without a password so i have to log in as Administrator and then set the password for the user on the interface)

Thanks

**Comment by Treize2** [comment]
I'll be very interested in the answer. 

Thx

**Comment by kevinleturc** [comment]
Hi,

To set a password to a user you can use `getProperties()` method on `User` object and set a value for the key `password`. This method is available since 2.4.

I close the issue.
