### ISSUE TITLE
Blob filename

### ISSUE THREAD

**Issue by kfrapin** [nuxeo/nuxeo-java-client#2]
# Version of the nuxeo java client
Version : 0.1

# Current problem
When fetching a blob via the nuxeo client : 
```
final NuxeoClient client = new NuxeoClient(url, username, password);
final Document document = client.repository().fetchDocumentById(id);
final Blob blob = document.fetchBlob();
```

The filename set into the `blob` object corresponds to a temporary name like `nx-3249828972020235203.tmp` instead of the real filename set in the `file:filename` property of the `document` object.

# Possible solutions
For consistency we could have two fields in the `Blob` class, one for the real filename and one for the temporary filename. 

Or we could just have one field with the real filename, which is what I do : 
```
final NuxeoClient client = new NuxeoClient(url, username, password);
final Document document = client.repository().fetchDocumentById(id);
final Blob blob = document.fetchBlob();
// Update the filename
blob.setFileName((String) document.getProperties().get("file:filename"));
```

**Comment by vpasquier** [comment]
Hello!

Thank you very much for your feedback!

I'm going to open this [ticket](https://jira.nuxeo.com/browse/JAVACLIENT-70) in our jira, you will be able to follow the change within it.

I will be glad to have lots of feedback. Im going to work intensively next days, please don't hesitate:)

1.0 java client release is expected in several weeks.

Thank you again!

**Comment by vpasquier** [comment]
And about your potential solution, it would be indeed a good idea, the problem is that the schema can be customized. (and i let in the API to specify the blob metadata but I will find a solution).

**Comment by kfrapin** [comment]
My pleasure!
You're right about the schema customisation, I didn't think about it.

I will probably open some tickets in the next few days for new features :) 

Thanks for that java client implementation.
