### ISSUE TITLE
not encode fieldPath

### ISSUE THREAD

**Issue by davarresc** [nuxeo/nuxeo-java-client#21]
Hi guys

Trying to retrieve the attachment of a document using the nuxeo client i get a bad request 400.
Check the following code:

`nuxeoClient.repository().fetchBlobById("e16ccdf8-cf29-4604-830e-8fc86eaba421","files:files/0/file");`

After further investigation i saw the nuxeo client is using retrofit http client to make the request, using the RepositoryAPI interface.

`    @GET("id/{documentId}/@blob/{fieldPath}")
    Call<Blob> fetchBlobById(@Path("documentId") String documentId, @Path("fieldPath") String fieldPath);`

The issue seems to be the attahcment path is being encoded, so the nexus client is making a request like:

http://localhost:8080/nuxeo/site/api/v1/id/e16ccdf8-cf29-4604-830e-8fc86eaba421/@blob/files:files%2F0%2Ffile

As you can see the path is encoded: files:files%2F0%2Ffile
I have modified the RepositoryAPI to not encode the fieldPath and now it is working.

`   @GET("id/{documentId}/@blob/{fieldPath}")
    Call<Blob> fetchBlobById(@Path("documentId") String documentId, @Path(value = "fieldPath", encoded = true) String fieldPath);`

encoded = true, it means to not encode the argument. 

I am wondering if the RepositoryAPI should include the encoded parameter as true for all fieldPath parameters, or the nuxeo repository should be able to manages the encoded urls.

If the RepositoryAPI should be modified to include the encode param as true in order to fix the issue i can create a PR with the fix.

Thanks.

**Comment by kevinleturc** [comment]
Hi @davarresc,

I created https://jira.nuxeo.com/browse/JAVACLIENT-124 to follow this issue. 

A PR will be welcomed with this bug fix and a test.

Then we will review your PR to merge it as soon as possible. Please don't forget to prefix your commit's message by {{JAVACLIENT-124:}}.

Thanks.

**Comment by kevinleturc** [comment]
Fix by #23
