### ISSUE TITLE
Object reconnection is not cached

### ISSUE THREAD

**Issue by A----** [nuxeo/nuxeo-java-client#29]
When there's a call to `NuxeoEntity.getResponse(…)`, the HTTP/API response is cached (if enabled, here https://github.com/nuxeo/nuxeo-java-client/blob/2.0/nuxeo-java-client/src/main/java/org/nuxeo/client/api/objects/NuxeoEntity.java#L151 .)

Body is then _reconnected_ (altered, by resetting properties from the API call headers, etc.)

On subsequent calls, the raw body will be retrieved from cache and sent back (here https://github.com/nuxeo/nuxeo-java-client/blob/2.0/nuxeo-java-client/src/main/java/org/nuxeo/client/api/objects/NuxeoEntity.java#L128 .)

When using the default cache manager, that works, as it shares the same instance. But if someone should use another manager, that will probably lead to some strange behaviors.

**Comment by kevinleturc** [comment]
Hi,
We probably won't improve this part on `2.0` branch, if the problem is still present on master we can improve this part.
Do you have a use case to lead the implementation/fix ?
