### ISSUE TITLE
Blob file

### ISSUE THREAD

**Issue by kfrapin** [nuxeo/nuxeo-java-client#3]
# Version of the nuxeo java client
Version : 0.1

# Current problem
In the old java automation client  there were two classes for dealing with the blobs entities : `StreamBlob` and `FileBlob`.

These two classes were able to keep the file content in-memory. 

`StreamBlob` was able to receive an `InputStream` as input in order to update a blob on the nuxeo server, like this :

```
StreamBlob streamBlob = new StreamBlob(new ByteArrayInputStream(content), filename, null);
session.newRequest(DocumentService.SetBlob)
    .setHeader(Constants.HEADER_NX_VOIDOP, "true")
    .setInput(streamBlob)
    .set("document", id)
    .execute();  
```

`FileBlob` was able to keep the data retrieved from the server as an `InputStream` too, like this :
```
FileBlob blob = (FileBlob) session.newRequest(DocumentService.GetBlob)
    .setHeader(Constants.HEADER_NX_SCHEMAS, "*")
    .setInput(document)
    .execute(); 
blob.getInputStream(); 
```

But now it seems that we have to deal with `io.File` which are written on the hard disk.

Perhaps I don't understand why, but isn't it better to keep file content in-memory instead of having i/o ?

# Possible solutions
We could have an `InputStream` attribute in the `Blob` class, or we could use the callback mechanism to directly stream the file content into an `OutputStream`.

**Comment by efge** [comment]
Keeping a file in memory should never be done. As soon as you need to upload a few big files it will trample all your memory and crash. So any upload solution should rely on an existing `File`, or on streaming from an `InputStream`.

**Comment by kfrapin** [comment]
Yes, you are right about big files and memory problems that can occur => _No more in-memory file content :)_

Just to be sure, do you agree with the following statements :

- **File download :** The `Blob` class could expose an `InputStream` attribute if we want to directly stream a file content (coming from the nuxeo server) to an `OuputStream` 

- **File upload :**  In the same way, we could use that `InputStream` if we want to directly stream data to the nuxeo server.

**Comment by efge** [comment]
I'll let @vpasquier comment.

**Comment by vpasquier** [comment]
Hello Kevin,

I'm very sorry I'm not sure to understand. So you would like to  get a simple method to return the stream from the file?
```
    public InputStream getStream() throws IOException {
        return new FileInputStream(file);
    }
```

Or you would like to have an inputstream attribute (meaning keeping the content in memory)?

Don't hesitate to change org.nuxeo.client.api.objects.blob.Blob to show me 

Thank you very much!

**Comment by kfrapin** [comment]
Hello Vladimir,
Don't worry, I haven't be pretty clear... and I was not on the right track :)

To answer your question : Yes, we could have a simple method returning a stream from the file ;)

just another question, do we have to manually handle the deletion of the files which are created by the `NuxeoClient` ?

**Comment by vpasquier** [comment]
Im gonna add this helper in Blob.

**Comment by vpasquier** [comment]
And for now you have to handle manually the deletion of the files so I'm gonna see if i can do it on the client side.

**Comment by vpasquier** [comment]
I added the help and a method to track the file (but you have to do it manually).

https://github.com/nuxeo/nuxeo-java-client/commit/707cd51e8eea3f2efe601c52a64f82366a7f0045

Thank you for your feedback!

**Comment by vpasquier** [comment]
And now, there is an example for Android in https://github.com/nuxeo/nuxeo-java-client/tree/master/NuxeoShare
