### ISSUE TITLE
Automation is not working

### ISSUE THREAD

**Issue by sirmad007** [nuxeo/nuxeo-java-client#4]
Hello

i tested the new nuxeo java client and it seems that all examples using automation are not working.

Example code:
`            
String url = "http://localhost:8080/nuxeo";

NuxeoClient nuxeoClient = new NuxeoClient(url, "Administrator", "Administrator").timeout(60).schemas("*");

Document result = nuxeoClient.automation().param("value", "/").execute("Repository.GetDocument");
`

This code leads to an Exception:
java.lang.ClassCastException: retrofit2.OkHttpCall$ExceptionCatchingRequestBody cannot be cast to org.nuxeo.client.api.objects.Document
	at testit.TestClient.main(TestClient.java:104)

the network traffic seems ok for me (see attachment)
![image](https://cloud.githubusercontent.com/assets/18436278/14486930/f5adb59a-015f-11e6-8e2f-2e9072c20366.png)

**Comment by vpasquier** [comment]
Thank you for your feedback. It's related to the fact you'd like to fetch the root document (for other documents it's working fine).

To fetch the root document of the repository you have a specific method `Document root = nuxeoClient.repository().fetchDocumentRoot();`. 

Here's the ticket https://jira.nuxeo.com/browse/JAVACLIENT-84 to follow.

Thank you very much for your feedback. Don't hesitate to give more! :)

**Comment by sirmad007** [comment]
i am not sure about it only happening with root
here another non-working example

> Documents result3 = nuxeoClient.automation("Repository.Query").param("query", "SELECT * FROM document").execute();

-> can you give me an working example of the automation() feature where the return type works?

**Comment by vpasquier** [comment]
So I just seen that tests was covering your examples and it's fully working even the root example:

https://github.com/nuxeo/nuxeo-java-client/blob/master/nuxeo-java-client-test/src/test/java/org/nuxeo/client/test/TestOperation.java#L71-L169

Are you using the 1.0 of the client?

**Comment by vpasquier** [comment]
If youre using this version, could you please give me all your codes + stack trace ? Java version etc?

Thank you very much

**Comment by vpasquier** [comment]
Don't hesitate to re-open the ticket if needed.

**Comment by kodo666** [comment]
I'm working with a Nuxeo 7.1 (Distribution date 201511092038) / JDK 1.8.0_60 and
have the same problems with "Automation" part of NuxeoClient.

Independently of the called method ("Repository.GetDocument", "Repository.Query") the result is

_java.lang.ClassCastException: retrofit2.OkHttpCall$ExceptionCatchingRequestBody cannot be cast to org.nuxeo.client.api.objects.Document

**Comment by vpasquier** [comment]
Hello,

So to clarify all of those problems with a Nuxeo Platform 7.10 LTS 2015, you have to download at least the HotFix 06 to make it work with the client because of https://jira.nuxeo.com/browse/NXP-18638. 

Thank you kodo666 for having given the version.

I'm investigating on how I could make it work on distribution without HF.
I keep you posted.

**Comment by vpasquier** [comment]
Thank you for your feedback.

This ticket has been created and the fix will be available for client 1.1 next week.

Meanwhile don’t hesitate to update your instance with the latest hotfix or if you can’t, test it with the FT 8.2 - http://www.nuxeo.com/downloads/

https://jira.nuxeo.com/browse/JAVACLIENT-86.
